name: Build and Release for Windows

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}  # Using GH_TOKEN to checkout private submodules if any

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install pyinstaller
          pip install flet  # Make sure to install Flet, not PyInstaller if you are using flet to pack

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --windowed --icon=quasi/gui/assets/icon/quasi_icon.ico quasi/gui/main.py --add-data "quasi/gui/assets;quasi/gui/assets"
          dir dist

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: packaged-app
          path: dist/  # Adjust this path based on where PyInstaller outputs your application

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: packaged-app
          path: output/  # Make sure this matches the upload path

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: output/*  # Ensure this path matches where the files are downloaded
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}  # This token is used to create the release
