version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Handler.Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - FLASK_ENV=development
    restart: always
