name: Build and Release

on:
  push:
    tags:
      - 'v*'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}  # Using GH_TOKEN to checkout private submodules if any

      - name: Setup SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_DEPLOY_KEY }}  # Use the name of your secret here

      - name: Test Clone Repository
        run: |
          ssh -T git@github.com || true # Ignore error
          git clone git@github.com:tqsd/photon_weave.git
        env:
          GIT_SSH_COMMAND: "ssh -v"

      - name: Test SSH Connection
        run: |
          set +e  # Do not exit immediately on non-zero return code
          ssh -T git@github.com
          set -e  # Turn back on the exit immediately on non-zero return code
        shell: bash
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install .  # Ensure this command is correct for installing your package
          pip install pyinstaller
          pip install flet  # Make sure to install Flet, not PyInstaller if you are using flet to pack

      - name: Build with Flet pack
        run: |
          echo "y" | flet pack quasi/gui/main.py --add-data "quasi/gui/assets:quasi/gui/assets"
          ls -l

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: packaged-app
          path: dist/  # Adjust this path based on where flet pack outputs your application

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: packaged-app
          path: output/  # Make sure this matches the upload path

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: output/*  # Ensure this path matches where the files are downloaded
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}  # This token is used to create the release
